#library program
library("bold")

#read in object, write as text file, remove object. repeat.

##all the lepidopterans
Acanthopteroctetidae <- bold_seqspec(taxon="Acanthopteroctetidae", marker="COI-5P")
write.table(Acanthopteroctetidae, file = "/home/orourke/R/Acanthopteroctetidae_taxmap_COI.txt", sep = "\t")
rm(Acanthopteroctetidae)
Adelidae <- bold_seqspec(taxon="Adelidae", marker="COI-5P")
write.table(Adelidae, file = "/home/orourke/R/Adelidae_taxmap_COI.txt", sep = "\t")
rm(Adelidae)
Agathiphagidae <- bold_seqspec(taxon="Agathiphagidae", marker="COI-5P")
write.table(Agathiphagidae, file = "/home/orourke/R/Agathiphagidae_taxmap_COI.txt", sep = "\t")
rm(Agathiphagidae)
Aididae <- bold_seqspec(taxon="Aididae", marker="COI-5P")
write.table(Aididae, file = "/home/orourke/R/Aididae_taxmap_COI.txt", sep = "\t")
rm(Aididae)
Alucitidae <- bold_seqspec(taxon="Alucitidae", marker="COI-5P")
write.table(Alucitidae, file = "/home/orourke/R/Alucitidae_taxmap_COI.txt", sep = "\t")
rm(Alucitidae)
Andesianidae <- bold_seqspec(taxon="Andesianidae", marker="COI-5P")
write.table(Andesianidae, file = "/home/orourke/R/Andesianidae_taxmap_COI.txt", sep = "\t")
rm(Andesianidae)
Anomosetidae <- bold_seqspec(taxon="Anomosetidae", marker="COI-5P")
write.table(Anomosetidae, file = "/home/orourke/R/Anomosetidae_taxmap_COI.txt", sep = "\t")
rm(Anomosetidae)
Anthelidae <- bold_seqspec(taxon="Anthelidae", marker="COI-5P")
write.table(Anthelidae, file = "/home/orourke/R/Anthelidae_taxmap_COI.txt", sep = "\t")
rm(Anthelidae)
Apatelodidae <- bold_seqspec(taxon="Apatelodidae", marker="COI-5P")
write.table(Apatelodidae, file = "/home/orourke/R/Apatelodidae_taxmap_COI.txt", sep = "\t")
rm(Apatelodidae)
Argyresthiidae <- bold_seqspec(taxon="Argyresthiidae", marker="COI-5P")
write.table(Argyresthiidae, file = "/home/orourke/R/Argyresthiidae_taxmap_COI.txt", sep = "\t")
rm(Argyresthiidae)
Attevidae <- bold_seqspec(taxon="Attevidae", marker="COI-5P")
write.table(Attevidae, file = "/home/orourke/R/Attevidae_taxmap_COI.txt", sep = "\t")
rm(Attevidae)
Autostichidae <- bold_seqspec(taxon="Autostichidae", marker="COI-5P")
write.table(Autostichidae, file = "/home/orourke/R/Autostichidae_taxmap_COI.txt", sep = "\t")
rm(Autostichidae)
Batrachedridae <- bold_seqspec(taxon="Batrachedridae", marker="COI-5P")
write.table(Batrachedridae, file = "/home/orourke/R/Batrachedridae_taxmap_COI.txt", sep = "\t")
rm(Batrachedridae)
Bedelliidae <- bold_seqspec(taxon="Bedelliidae", marker="COI-5P")
write.table(Bedelliidae, file = "/home/orourke/R/Bedelliidae_taxmap_COI.txt", sep = "\t")
rm(Bedelliidae)
Blastobasidae <- bold_seqspec(taxon="Blastobasidae", marker="COI-5P")
write.table(Blastobasidae, file = "/home/orourke/R/Blastobasidae_taxmap_COI.txt", sep = "\t")
rm(Blastobasidae)
Bombycidae <- bold_seqspec(taxon="Bombycidae", marker="COI-5P")
write.table(Bombycidae, file = "/home/orourke/R/Bombycidae_taxmap_COI.txt", sep = "\t")
rm(Bombycidae)
Brachodidae <- bold_seqspec(taxon="Brachodidae", marker="COI-5P")
write.table(Brachodidae, file = "/home/orourke/R/Brachodidae_taxmap_COI.txt", sep = "\t")
rm(Brachodidae)
Brahmaeidae <- bold_seqspec(taxon="Brahmaeidae", marker="COI-5P")
write.table(Brahmaeidae, file = "/home/orourke/R/Brahmaeidae_taxmap_COI.txt", sep = "\t")
rm(Brahmaeidae)
Bucculatricidae <- bold_seqspec(taxon="Bucculatricidae", marker="COI-5P")
write.table(Bucculatricidae, file = "/home/orourke/R/Bucculatricidae_taxmap_COI.txt", sep = "\t")
rm(Bucculatricidae)
Callidulidae <- bold_seqspec(taxon="Callidulidae", marker="COI-5P")
write.table(Callidulidae, file = "/home/orourke/R/Callidulidae_taxmap_COI.txt", sep = "\t")
rm(Callidulidae)
Carposinidae <- bold_seqspec(taxon="Carposinidae", marker="COI-5P")
write.table(Carposinidae, file = "/home/orourke/R/Carposinidae_taxmap_COI.txt", sep = "\t")
rm(Carposinidae)
Carthaeidae <- bold_seqspec(taxon="Carthaeidae", marker="COI-5P")
write.table(Carthaeidae, file = "/home/orourke/R/Carthaeidae_taxmap_COI.txt", sep = "\t")
rm(Carthaeidae)
Castniidae <- bold_seqspec(taxon="Castniidae", marker="COI-5P")
write.table(Castniidae, file = "/home/orourke/R/Castniidae_taxmap_COI.txt", sep = "\t")
rm(Castniidae)
Cecidosidae <- bold_seqspec(taxon="Cecidosidae", marker="COI-5P")
write.table(Cecidosidae, file = "/home/orourke/R/Cecidosidae_taxmap_COI.txt", sep = "\t")
rm(Cecidosidae)
Choreutidae <- bold_seqspec(taxon="Choreutidae", marker="COI-5P")
write.table(Choreutidae, file = "/home/orourke/R/Choreutidae_taxmap_COI.txt", sep = "\t")
rm(Choreutidae)
Cimeliidae <- bold_seqspec(taxon="Cimeliidae", marker="COI-5P")
write.table(Cimeliidae, file = "/home/orourke/R/Cimeliidae_taxmap_COI.txt", sep = "\t")
rm(Cimeliidae)
Coleophoridae <- bold_seqspec(taxon="Coleophoridae", marker="COI-5P")
write.table(Coleophoridae, file = "/home/orourke/R/Coleophoridae_taxmap_COI.txt", sep = "\t")
rm(Coleophoridae)
Copromorphidae <- bold_seqspec(taxon="Copromorphidae", marker="COI-5P")
write.table(Copromorphidae, file = "/home/orourke/R/Copromorphidae_taxmap_COI.txt", sep = "\t")
rm(Copromorphidae)
Cosmopterigidae <- bold_seqspec(taxon="Cosmopterigidae", marker="COI-5P")
write.table(Cosmopterigidae, file = "/home/orourke/R/Cosmopterigidae_taxmap_COI.txt", sep = "\t")
rm(Cosmopterigidae)
Cossidae <- bold_seqspec(taxon="Cossidae", marker="COI-5P")
write.table(Cossidae, file = "/home/orourke/R/Cossidae_taxmap_COI.txt", sep = "\t")
rm(Cossidae)
Crambidae <- bold_seqspec(taxon="Crambidae", marker="COI-5P")
write.table(Crambidae, file = "/home/orourke/R/Crambidae_taxmap_COI.txt", sep = "\t")
rm(Crambidae)
Cyclotornidae <- bold_seqspec(taxon="Cyclotornidae", marker="COI-5P")
write.table(Cyclotornidae, file = "/home/orourke/R/Cyclotornidae_taxmap_COI.txt", sep = "\t")
rm(Cyclotornidae)
Dalceridae <- bold_seqspec(taxon="Dalceridae", marker="COI-5P")
write.table(Dalceridae, file = "/home/orourke/R/Dalceridae_taxmap_COI.txt", sep = "\t")
rm(Dalceridae)
Depressariidae <- bold_seqspec(taxon="Depressariidae", marker="COI-5P")
write.table(Depressariidae, file = "/home/orourke/R/Depressariidae_taxmap_COI.txt", sep = "\t")
rm(Depressariidae)
Doidae <- bold_seqspec(taxon="Doidae", marker="COI-5P")
write.table(Doidae, file = "/home/orourke/R/Doidae_taxmap_COI.txt", sep = "\t")
rm(Doidae)
Douglasiidae <- bold_seqspec(taxon="Douglasiidae", marker="COI-5P")
write.table(Douglasiidae, file = "/home/orourke/R/Douglasiidae_taxmap_COI.txt", sep = "\t")
rm(Douglasiidae)
Drepanidae <- bold_seqspec(taxon="Drepanidae", marker="COI-5P")
write.table(Drepanidae, file = "/home/orourke/R/Drepanidae_taxmap_COI.txt", sep = "\t")
rm(Drepanidae)
Dudgeoneidae <- bold_seqspec(taxon="Dudgeoneidae", marker="COI-5P")
write.table(Dudgeoneidae, file = "/home/orourke/R/Dudgeoneidae_taxmap_COI.txt", sep = "\t")
rm(Dudgeoneidae)
Elachistidae <- bold_seqspec(taxon="Elachistidae", marker="COI-5P")
write.table(Elachistidae, file = "/home/orourke/R/Elachistidae_taxmap_COI.txt", sep = "\t")
rm(Elachistidae)
Endromidae <- bold_seqspec(taxon="Endromidae", marker="COI-5P")
write.table(Endromidae, file = "/home/orourke/R/Endromidae_taxmap_COI.txt", sep = "\t")
rm(Endromidae)
Epermeniidae <- bold_seqspec(taxon="Epermeniidae", marker="COI-5P")
write.table(Epermeniidae, file = "/home/orourke/R/Epermeniidae_taxmap_COI.txt", sep = "\t")
rm(Epermeniidae)
Epicopeiidae <- bold_seqspec(taxon="Epicopeiidae", marker="COI-5P")
write.table(Epicopeiidae, file = "/home/orourke/R/Epicopeiidae_taxmap_COI.txt", sep = "\t")
rm(Epicopeiidae)
Epipyropidae <- bold_seqspec(taxon="Epipyropidae", marker="COI-5P")
write.table(Epipyropidae, file = "/home/orourke/R/Epipyropidae_taxmap_COI.txt", sep = "\t")
rm(Epipyropidae)
Erebidae <- bold_seqspec(taxon="Erebidae", marker="COI-5P")
write.table(Erebidae, file = "/home/orourke/R/Erebidae_taxmap_COI.txt", sep = "\t")
rm(Erebidae)
Eriocottidae <- bold_seqspec(taxon="Eriocottidae", marker="COI-5P")
write.table(Eriocottidae, file = "/home/orourke/R/Eriocottidae_taxmap_COI.txt", sep = "\t")
rm(Eriocottidae)
Eriocraniidae <- bold_seqspec(taxon="Eriocraniidae", marker="COI-5P")
write.table(Eriocraniidae, file = "/home/orourke/R/Eriocraniidae_taxmap_COI.txt", sep = "\t")
rm(Eriocraniidae)
Eupterotidae <- bold_seqspec(taxon="Eupterotidae", marker="COI-5P")
write.table(Eupterotidae, file = "/home/orourke/R/Eupterotidae_taxmap_COI.txt", sep = "\t")
rm(Eupterotidae)
Euteliidae <- bold_seqspec(taxon="Euteliidae", marker="COI-5P")
write.table(Euteliidae, file = "/home/orourke/R/Euteliidae_taxmap_COI.txt", sep = "\t")
rm(Euteliidae)
Galacticidae <- bold_seqspec(taxon="Galacticidae", marker="COI-5P")
write.table(Galacticidae, file = "/home/orourke/R/Galacticidae_taxmap_COI.txt", sep = "\t")
rm(Galacticidae)
Gelechiidae <- bold_seqspec(taxon="Gelechiidae", marker="COI-5P")
write.table(Gelechiidae, file = "/home/orourke/R/Gelechiidae_taxmap_COI.txt", sep = "\t")
rm(Gelechiidae)
Geometridae <- bold_seqspec(taxon="Geometridae", marker="COI-5P")
write.table(Geometridae, file = "/home/orourke/R/Geometridae_taxmap_COI.txt", sep = "\t")
rm(Geometridae)
Glyphipterigidae <- bold_seqspec(taxon="Glyphipterigidae", marker="COI-5P")
write.table(Glyphipterigidae, file = "/home/orourke/R/Glyphipterigidae_taxmap_COI.txt", sep = "\t")
rm(Glyphipterigidae)
Gracillariidae <- bold_seqspec(taxon="Gracillariidae", marker="COI-5P")
write.table(Gracillariidae, file = "/home/orourke/R/Gracillariidae_taxmap_COI.txt", sep = "\t")
rm(Gracillariidae)
Hedylidae <- bold_seqspec(taxon="Hedylidae", marker="COI-5P")
write.table(Hedylidae, file = "/home/orourke/R/Hedylidae_taxmap_COI.txt", sep = "\t")
rm(Hedylidae)
Heliodinidae <- bold_seqspec(taxon="Heliodinidae", marker="COI-5P")
write.table(Heliodinidae, file = "/home/orourke/R/Heliodinidae_taxmap_COI.txt", sep = "\t")
rm(Heliodinidae)
Heliozelidae <- bold_seqspec(taxon="Heliozelidae", marker="COI-5P")
write.table(Heliozelidae, file = "/home/orourke/R/Heliozelidae_taxmap_COI.txt", sep = "\t")
rm(Heliozelidae)
Hepialidae <- bold_seqspec(taxon="Hepialidae", marker="COI-5P")
write.table(Hepialidae, file = "/home/orourke/R/Hepialidae_taxmap_COI.txt", sep = "\t")
rm(Hepialidae)
Hesperiidae <- bold_seqspec(taxon="Hesperiidae", marker="COI-5P")
write.table(Hesperiidae, file = "/home/orourke/R/Hesperiidae_taxmap_COI.txt", sep = "\t")
rm(Hesperiidae)
Heterobathmiidae <- bold_seqspec(taxon="Heterobathmiidae", marker="COI-5P")
write.table(Heterobathmiidae, file = "/home/orourke/R/Heterobathmiidae_taxmap_COI.txt", sep = "\t")
rm(Heterobathmiidae)
Heterogynidae <- bold_seqspec(taxon="Heterogynidae", marker="COI-5P")
write.table(Heterogynidae, file = "/home/orourke/R/Heterogynidae_taxmap_COI.txt", sep = "\t")
rm(Heterogynidae)
Himantopteridae <- bold_seqspec(taxon="Himantopteridae", marker="COI-5P")
write.table(Himantopteridae, file = "/home/orourke/R/Himantopteridae_taxmap_COI.txt", sep = "\t")
rm(Himantopteridae)
Hyblaeidae <- bold_seqspec(taxon="Hyblaeidae", marker="COI-5P")
write.table(Hyblaeidae, file = "/home/orourke/R/Hyblaeidae_taxmap_COI.txt", sep = "\t")
rm(Hyblaeidae)
Immidae <- bold_seqspec(taxon="Immidae", marker="COI-5P")
write.table(Immidae, file = "/home/orourke/R/Immidae_taxmap_COI.txt", sep = "\t")
rm(Immidae)
Incurvariidae <- bold_seqspec(taxon="Incurvariidae", marker="COI-5P")
write.table(Incurvariidae, file = "/home/orourke/R/Incurvariidae_taxmap_COI.txt", sep = "\t")
rm(Incurvariidae)
Lacturidae <- bold_seqspec(taxon="Lacturidae", marker="COI-5P")
write.table(Lacturidae, file = "/home/orourke/R/Lacturidae_taxmap_COI.txt", sep = "\t")
rm(Lacturidae)
Lasiocampidae <- bold_seqspec(taxon="Lasiocampidae", marker="COI-5P")
write.table(Lasiocampidae, file = "/home/orourke/R/Lasiocampidae_taxmap_COI.txt", sep = "\t")
rm(Lasiocampidae)
Lecithoceridae <- bold_seqspec(taxon="Lecithoceridae", marker="COI-5P")
write.table(Lecithoceridae, file = "/home/orourke/R/Lecithoceridae_taxmap_COI.txt", sep = "\t")
rm(Lecithoceridae)
Lepidoptera_incertae_sedis <- bold_seqspec(taxon="Lepidoptera_incertae_sedis", marker="COI-5P")
write.table(Lepidoptera_incertae_sedis, file = "/home/orourke/R/Lepidoptera_incertae_sedis_taxmap_COI.txt", sep = "\t")
rm(Lepidoptera_incertae_sedis)
Limacodidae <- bold_seqspec(taxon="Limacodidae", marker="COI-5P")
write.table(Limacodidae, file = "/home/orourke/R/Limacodidae_taxmap_COI.txt", sep = "\t")
rm(Limacodidae)
Lophocoronidae <- bold_seqspec(taxon="Lophocoronidae", marker="COI-5P")
write.table(Lophocoronidae, file = "/home/orourke/R/Lophocoronidae_taxmap_COI.txt", sep = "\t")
rm(Lophocoronidae)
Lycaenidae <- bold_seqspec(taxon="Lycaenidae", marker="COI-5P")
write.table(Lycaenidae, file = "/home/orourke/R/Lycaenidae_taxmap_COI.txt", sep = "\t")
rm(Lycaenidae)
Lyonetiidae <- bold_seqspec(taxon="Lyonetiidae", marker="COI-5P")
write.table(Lyonetiidae, file = "/home/orourke/R/Lyonetiidae_taxmap_COI.txt", sep = "\t")
rm(Lyonetiidae)
Lypusidae <- bold_seqspec(taxon="Lypusidae", marker="COI-5P")
write.table(Lypusidae, file = "/home/orourke/R/Lypusidae_taxmap_COI.txt", sep = "\t")
rm(Lypusidae)
Megalopygidae <- bold_seqspec(taxon="Megalopygidae", marker="COI-5P")
write.table(Megalopygidae, file = "/home/orourke/R/Megalopygidae_taxmap_COI.txt", sep = "\t")
rm(Megalopygidae)
#CAUTION!! there was an error in BOLD's database specifying this term. It apparently has a misspelling. This has been accounted for in the taxon term but not changed in terms of the name of the object or the file (as that is actually the correct spelling)
Metarbelidae <- bold_seqspec(taxon="Metarbelinae", marker="COI-5P")
write.table(Metarbelidae, file = "/home/orourke/R/Metarbelidae_taxmap_COI.txt", sep = "\t")
rm(Metarbelidae)
Micropterigidae <- bold_seqspec(taxon="Micropterigidae", marker="COI-5P")
write.table(Micropterigidae, file = "/home/orourke/R/Micropterigidae_taxmap_COI.txt", sep = "\t")
rm(Micropterigidae)
Millieriidae <- bold_seqspec(taxon="Millieriidae", marker="COI-5P")
write.table(Millieriidae, file = "/home/orourke/R/Millieriidae_taxmap_COI.txt", sep = "\t")
rm(Millieriidae)
Mimallonidae <- bold_seqspec(taxon="Mimallonidae", marker="COI-5P")
write.table(Mimallonidae, file = "/home/orourke/R/Mimallonidae_taxmap_COI.txt", sep = "\t")
rm(Mimallonidae)
Mnesarchaeidae <- bold_seqspec(taxon="Mnesarchaeidae", marker="COI-5P")
write.table(Mnesarchaeidae, file = "/home/orourke/R/Mnesarchaeidae_taxmap_COI.txt", sep = "\t")
rm(Mnesarchaeidae)
Momphidae <- bold_seqspec(taxon="Momphidae", marker="COI-5P")
write.table(Momphidae, file = "/home/orourke/R/Momphidae_taxmap_COI.txt", sep = "\t")
rm(Momphidae)
Neopseustidae <- bold_seqspec(taxon="Neopseustidae", marker="COI-5P")
write.table(Neopseustidae, file = "/home/orourke/R/Neopseustidae_taxmap_COI.txt", sep = "\t")
rm(Neopseustidae)
Nepticulidae <- bold_seqspec(taxon="Nepticulidae", marker="COI-5P")
write.table(Nepticulidae, file = "/home/orourke/R/Nepticulidae_taxmap_COI.txt", sep = "\t")
rm(Nepticulidae)
Noctuidae <- bold_seqspec(taxon="Noctuidae", marker="COI-5P")
write.table(Noctuidae, file = "/home/orourke/R/Noctuidae_taxmap_COI.txt", sep = "\t")
rm(Noctuidae)
Nolidae <- bold_seqspec(taxon="Nolidae", marker="COI-5P")
write.table(Nolidae, file = "/home/orourke/R/Nolidae_taxmap_COI.txt", sep = "\t")
rm(Nolidae)
Notodontidae <- bold_seqspec(taxon="Notodontidae", marker="COI-5P")
write.table(Notodontidae, file = "/home/orourke/R/Notodontidae_taxmap_COI.txt", sep = "\t")
rm(Notodontidae)
Nymphalidae <- bold_seqspec(taxon="Nymphalidae", marker="COI-5P")
write.table(Nymphalidae, file = "/home/orourke/R/Nymphalidae_taxmap_COI.txt", sep = "\t")
rm(Nymphalidae)
Oecophoridae <- bold_seqspec(taxon="Oecophoridae", marker="COI-5P")
write.table(Oecophoridae, file = "/home/orourke/R/Oecophoridae_taxmap_COI.txt", sep = "\t")
rm(Oecophoridae)
Oenosandridae <- bold_seqspec(taxon="Oenosandridae", marker="COI-5P")
write.table(Oenosandridae, file = "/home/orourke/R/Oenosandridae_taxmap_COI.txt", sep = "\t")
rm(Oenosandridae)
Opostegidae <- bold_seqspec(taxon="Opostegidae", marker="COI-5P")
write.table(Opostegidae, file = "/home/orourke/R/Opostegidae_taxmap_COI.txt", sep = "\t")
rm(Opostegidae)
Palaeosetidae <- bold_seqspec(taxon="Palaeosetidae", marker="COI-5P")
write.table(Palaeosetidae, file = "/home/orourke/R/Palaeosetidae_taxmap_COI.txt", sep = "\t")
rm(Palaeosetidae)
Palaephatidae <- bold_seqspec(taxon="Palaephatidae", marker="COI-5P")
write.table(Palaephatidae, file = "/home/orourke/R/Palaephatidae_taxmap_COI.txt", sep = "\t")
rm(Palaephatidae)
Papilionidae <- bold_seqspec(taxon="Papilionidae", marker="COI-5P")
write.table(Papilionidae, file = "/home/orourke/R/Papilionidae_taxmap_COI.txt", sep = "\t")
rm(Papilionidae)
Phaudidae <- bold_seqspec(taxon="Phaudidae", marker="COI-5P")
write.table(Phaudidae, file = "/home/orourke/R/Phaudidae_taxmap_COI.txt", sep = "\t")
rm(Phaudidae)
Phiditiidae <- bold_seqspec(taxon="Phiditiidae", marker="COI-5P")
write.table(Phiditiidae, file = "/home/orourke/R/Phiditiidae_taxmap_COI.txt", sep = "\t")
rm(Phiditiidae)
Pieridae <- bold_seqspec(taxon="Pieridae", marker="COI-5P")
write.table(Pieridae, file = "/home/orourke/R/Pieridae_taxmap_COI.txt", sep = "\t")
rm(Pieridae)
Plutellidae <- bold_seqspec(taxon="Plutellidae", marker="COI-5P")
write.table(Plutellidae, file = "/home/orourke/R/Plutellidae_taxmap_COI.txt", sep = "\t")
rm(Plutellidae)
Praydidae <- bold_seqspec(taxon="Praydidae", marker="COI-5P")
write.table(Praydidae, file = "/home/orourke/R/Praydidae_taxmap_COI.txt", sep = "\t")
rm(Praydidae)

##another likely source of error. can't find public data url. only 2 representatives so not going to include.
#Prodidactidae <- bold_seqspec(taxon="Prodidactidae", marker="COI-5P")
#write.table(Prodidactidae, file = "/home/orourke/R/Prodidactidae_taxmap_COI.txt", sep = "\t")
#rm(Prodidactidae)

Prodoxidae <- bold_seqspec(taxon="Prodoxidae", marker="COI-5P")
write.table(Prodoxidae, file = "/home/orourke/R/Prodoxidae_taxmap_COI.txt", sep = "\t")
rm(Prodoxidae)
Prototheoridae <- bold_seqspec(taxon="Prototheoridae", marker="COI-5P")
write.table(Prototheoridae, file = "/home/orourke/R/Prototheoridae_taxmap_COI.txt", sep = "\t")
rm(Prototheoridae)
Pseudobistonidae <- bold_seqspec(taxon="Pseudobistonidae", marker="COI-5P")
write.table(Pseudobistonidae, file = "/home/orourke/R/Pseudobistonidae_taxmap_COI.txt", sep = "\t")
rm(Pseudobistonidae)
Psychidae <- bold_seqspec(taxon="Psychidae", marker="COI-5P")
write.table(Psychidae, file = "/home/orourke/R/Psychidae_taxmap_COI.txt", sep = "\t")
rm(Psychidae)
Pterolonchidae <- bold_seqspec(taxon="Pterolonchidae", marker="COI-5P")
write.table(Pterolonchidae, file = "/home/orourke/R/Pterolonchidae_taxmap_COI.txt", sep = "\t")
rm(Pterolonchidae)
Pterophoridae <- bold_seqspec(taxon="Pterophoridae", marker="COI-5P")
write.table(Pterophoridae, file = "/home/orourke/R/Pterophoridae_taxmap_COI.txt", sep = "\t")
rm(Pterophoridae)
Pyralidae <- bold_seqspec(taxon="Pyralidae", marker="COI-5P")
write.table(Pyralidae, file = "/home/orourke/R/Pyralidae_taxmap_COI.txt", sep = "\t")
rm(Pyralidae)

#same issue as above with Prodidactidae. Only 2 sequences lost.
#Ratardidae <- bold_seqspec(taxon="Ratardidae", marker="COI-5P")
#write.table(Ratardidae, file = "/home/orourke/R/Ratardidae_taxmap_COI.txt", sep = "\t")
#rm(Ratardidae)

Riodinidae <- bold_seqspec(taxon="Riodinidae", marker="COI-5P")
write.table(Riodinidae, file = "/home/orourke/R/Riodinidae_taxmap_COI.txt", sep = "\t")
rm(Riodinidae)
Roeslerstammiidae <- bold_seqspec(taxon="Roeslerstammiidae", marker="COI-5P")
write.table(Roeslerstammiidae, file = "/home/orourke/R/Roeslerstammiidae_taxmap_COI.txt", sep = "\t")
rm(Roeslerstammiidae)
Saturniidae <- bold_seqspec(taxon="Saturniidae", marker="COI-5P")
write.table(Saturniidae, file = "/home/orourke/R/Saturniidae_taxmap_COI.txt", sep = "\t")
rm(Saturniidae)

##same issue as above
#Schistonoeidae <- bold_seqspec(taxon="Schistonoeidae", marker="COI-5P")
#write.table(Schistonoeidae, file = "/home/orourke/R/Schistonoeidae_taxmap_COI.txt", sep = "\t")
#rm(Schistonoeidae)

Schreckensteiniidae <- bold_seqspec(taxon="Schreckensteiniidae", marker="COI-5P")
write.table(Schreckensteiniidae, file = "/home/orourke/R/Schreckensteiniidae_taxmap_COI.txt", sep = "\t")
rm(Schreckensteiniidae)
Scythrididae <- bold_seqspec(taxon="Scythrididae", marker="COI-5P")
write.table(Scythrididae, file = "/home/orourke/R/Scythrididae_taxmap_COI.txt", sep = "\t")
rm(Scythrididae)
Sematuridae <- bold_seqspec(taxon="Sematuridae", marker="COI-5P")
write.table(Sematuridae, file = "/home/orourke/R/Sematuridae_taxmap_COI.txt", sep = "\t")
rm(Sematuridae)
Sesiidae <- bold_seqspec(taxon="Sesiidae", marker="COI-5P")
write.table(Sesiidae, file = "/home/orourke/R/Sesiidae_taxmap_COI.txt", sep = "\t")
rm(Sesiidae)
Simaethistidae <- bold_seqspec(taxon="Simaethistidae", marker="COI-5P")
write.table(Simaethistidae, file = "/home/orourke/R/Simaethistidae_taxmap_COI.txt", sep = "\t")
rm(Simaethistidae)

##same issue as above
#Somabrachyidae <- bold_seqspec(taxon="Somabrachyidae", marker="COI-5P")
#write.table(Somabrachyidae, file = "/home/orourke/R/Somabrachyidae_taxmap_COI.txt", sep = "\t")
#rm(Somabrachyidae)

Sphingidae <- bold_seqspec(taxon="Sphingidae", marker="COI-5P")
write.table(Sphingidae, file = "/home/orourke/R/Sphingidae_taxmap_COI.txt", sep = "\t")
rm(Sphingidae)
Stathmopodidae <- bold_seqspec(taxon="Stathmopodidae", marker="COI-5P")
write.table(Stathmopodidae, file = "/home/orourke/R/Stathmopodidae_taxmap_COI.txt", sep = "\t")
rm(Stathmopodidae)
Thyrididae <- bold_seqspec(taxon="Thyrididae", marker="COI-5P")
write.table(Thyrididae, file = "/home/orourke/R/Thyrididae_taxmap_COI.txt", sep = "\t")
rm(Thyrididae)
Tineidae <- bold_seqspec(taxon="Tineidae", marker="COI-5P")
write.table(Tineidae, file = "/home/orourke/R/Tineidae_taxmap_COI.txt", sep = "\t")
rm(Tineidae)
Tineodidae <- bold_seqspec(taxon="Tineodidae", marker="COI-5P")
write.table(Tineodidae, file = "/home/orourke/R/Tineodidae_taxmap_COI.txt", sep = "\t")
rm(Tineodidae)
Tischeriidae <- bold_seqspec(taxon="Tischeriidae", marker="COI-5P")
write.table(Tischeriidae, file = "/home/orourke/R/Tischeriidae_taxmap_COI.txt", sep = "\t")
rm(Tischeriidae)
Tortricidae <- bold_seqspec(taxon="Tortricidae", marker="COI-5P")
write.table(Tortricidae, file = "/home/orourke/R/Tortricidae_taxmap_COI.txt", sep = "\t")
rm(Tortricidae)

##Tridentaformidae <- bold_seqspec(taxon="Tridentaformidae", marker="COI-5P")
##write.table(Tridentaformidae, file = "/home/orourke/R/Tridentaformidae_taxmap_COI.txt", sep = "\t")
##rm(Tridentaformidae)

Uraniidae <- bold_seqspec(taxon="Uraniidae", marker="COI-5P")
write.table(Uraniidae, file = "/home/orourke/R/Uraniidae_taxmap_COI.txt", sep = "\t")
rm(Uraniidae)
Urodidae <- bold_seqspec(taxon="Urodidae", marker="COI-5P")
write.table(Urodidae, file = "/home/orourke/R/Urodidae_taxmap_COI.txt", sep = "\t")
rm(Urodidae)

##Whalleyanidae <- bold_seqspec(taxon="Whalleyanidae", marker="COI-5P")
##write.table(Whalleyanidae, file = "/home/orourke/R/Whalleyanidae_taxmap_COI.txt", sep = "\t")
##rm(Whalleyanidae)

Xyloryctidae <- bold_seqspec(taxon="Xyloryctidae", marker="COI-5P")
write.table(Xyloryctidae, file = "/home/orourke/R/Xyloryctidae_taxmap_COI.txt", sep = "\t")
rm(Xyloryctidae)
Yponomeutidae <- bold_seqspec(taxon="Yponomeutidae", marker="COI-5P")
write.table(Yponomeutidae, file = "/home/orourke/R/Yponomeutidae_taxmap_COI.txt", sep = "\t")
rm(Yponomeutidae)
Ypsolophidae <- bold_seqspec(taxon="Ypsolophidae", marker="COI-5P")
write.table(Ypsolophidae, file = "/home/orourke/R/Ypsolophidae_taxmap_COI.txt", sep = "\t")
rm(Ypsolophidae)
Zygaenidae <- bold_seqspec(taxon="Zygaenidae", marker="COI-5P")
write.table(Zygaenidae, file = "/home/orourke/R/Zygaenidae_taxmap_COI.txt", sep = "\t")
rm(Zygaenidae)

##all the insects not lepidopterans
Archaeognatha <- bold_seqspec(taxon="Archaeognatha", marker="COI-5P")
write.table(Archaeognatha, file = "/home/orourke/R/Archaeognatha_taxmap_COI.txt", sep = "\t")
rm(Archaeognatha)
Blattodea <- bold_seqspec(taxon="Blattodea", marker="COI-5P")
write.table(Blattodea, file = "/home/orourke/R/Blattodea_taxmap_COI.txt", sep = "\t")
rm(Blattodea)
Coleoptera <- bold_seqspec(taxon="Coleoptera", marker="COI-5P")
write.table(Coleoptera, file = "/home/orourke/R/Coleoptera_taxmap_COI.txt", sep = "\t")
rm(Coleoptera)
Dermaptera <- bold_seqspec(taxon="Dermaptera", marker="COI-5P")
write.table(Dermaptera, file = "/home/orourke/R/Dermaptera_taxmap_COI.txt", sep = "\t")
rm(Dermaptera)
Diptera <- bold_seqspec(taxon="Diptera", marker="COI-5P")
write.table(Diptera, file = "/home/orourke/R/Diptera_taxmap_COI.txt", sep = "\t")
rm(Diptera)
Embioptera <- bold_seqspec(taxon="Embioptera", marker="COI-5P")
write.table(Embioptera, file = "/home/orourke/R/Embioptera_taxmap_COI.txt", sep = "\t")
rm(Embioptera)
Ephemeroptera <- bold_seqspec(taxon="Ephemeroptera", marker="COI-5P")
write.table(Ephemeroptera, file = "/home/orourke/R/Ephemeroptera_taxmap_COI.txt", sep = "\t")
rm(Ephemeroptera)
Grylloblattodea <- bold_seqspec(taxon="Grylloblattodea", marker="COI-5P")
write.table(Grylloblattodea, file = "/home/orourke/R/Grylloblattodea_taxmap_COI.txt", sep = "\t")
rm(Grylloblattodea)
Hemiptera <- bold_seqspec(taxon="Hemiptera", marker="COI-5P")
write.table(Hemiptera, file = "/home/orourke/R/Hemiptera_taxmap_COI.txt", sep = "\t")
rm(Hemiptera)
Hymenoptera <- bold_seqspec(taxon="Hymenoptera", marker="COI-5P")
write.table(Hymenoptera, file = "/home/orourke/R/Hymenoptera_taxmap_COI.txt", sep = "\t")
rm(Hymenoptera)
Isoptera <- bold_seqspec(taxon="Isoptera", marker="COI-5P")
write.table(Isoptera, file = "/home/orourke/R/Isoptera_taxmap_COI.txt", sep = "\t")
rm(Isoptera)
Mantodea <- bold_seqspec(taxon="Mantodea", marker="COI-5P")
write.table(Mantodea, file = "/home/orourke/R/Mantodea_taxmap_COI.txt", sep = "\t")
rm(Mantodea)
Mecoptera <- bold_seqspec(taxon="Mecoptera", marker="COI-5P")
write.table(Mecoptera, file = "/home/orourke/R/Mecoptera_taxmap_COI.txt", sep = "\t")
rm(Mecoptera)
Megaloptera <- bold_seqspec(taxon="Megaloptera", marker="COI-5P")
write.table(Megaloptera, file = "/home/orourke/R/Megaloptera_taxmap_COI.txt", sep = "\t")
rm(Megaloptera)
Neuroptera <- bold_seqspec(taxon="Neuroptera", marker="COI-5P")
write.table(Neuroptera, file = "/home/orourke/R/Neuroptera_taxmap_COI.txt", sep = "\t")
rm(Neuroptera)
Odonata <- bold_seqspec(taxon="Odonata", marker="COI-5P")
write.table(Odonata, file = "/home/orourke/R/Odonata_taxmap_COI.txt", sep = "\t")
rm(Odonata)
Orthoptera <- bold_seqspec(taxon="Orthoptera", marker="COI-5P")
write.table(Orthoptera, file = "/home/orourke/R/Orthoptera_taxmap_COI.txt", sep = "\t")
rm(Orthoptera)
Phasmatodea <- bold_seqspec(taxon="Phasmatodea", marker="COI-5P")
write.table(Phasmatodea, file = "/home/orourke/R/Phasmatodea_taxmap_COI.txt", sep = "\t")
rm(Phasmatodea)
Plecoptera <- bold_seqspec(taxon="Plecoptera", marker="COI-5P")
write.table(Plecoptera, file = "/home/orourke/R/Plecoptera_taxmap_COI.txt", sep = "\t")
rm(Plecoptera)
Psocodea <- bold_seqspec(taxon="Psocodea", marker="COI-5P")
write.table(Psocodea, file = "/home/orourke/R/Psocodea_taxmap_COI.txt", sep = "\t")
rm(Psocodea)
Raphidioptera <- bold_seqspec(taxon="Raphidioptera", marker="COI-5P")
write.table(Raphidioptera, file = "/home/orourke/R/Raphidioptera_taxmap_COI.txt", sep = "\t")
rm(Raphidioptera)
Siphonaptera <- bold_seqspec(taxon="Siphonaptera", marker="COI-5P")
write.table(Siphonaptera, file = "/home/orourke/R/Siphonaptera_taxmap_COI.txt", sep = "\t")
rm(Siphonaptera)
Strepsiptera <- bold_seqspec(taxon="Strepsiptera", marker="COI-5P")
write.table(Strepsiptera, file = "/home/orourke/R/Strepsiptera_taxmap_COI.txt", sep = "\t")
rm(Strepsiptera)
Thysanoptera <- bold_seqspec(taxon="Thysanoptera", marker="COI-5P")
write.table(Thysanoptera, file = "/home/orourke/R/Thysanoptera_taxmap_COI.txt", sep = "\t")
rm(Thysanoptera)
Thysanura <- bold_seqspec(taxon="Thysanura", marker="COI-5P")
write.table(Thysanura, file = "/home/orourke/R/Thysanura_taxmap_COI.txt", sep = "\t")
rm(Thysanura)
Trichoptera <- bold_seqspec(taxon="Trichoptera", marker="COI-5P")
write.table(Trichoptera, file = "/home/orourke/R/Trichoptera_taxmap_COI.txt", sep = "\t")
rm(Trichoptera)

##Zoraptera <- bold_seqspec(taxon="Zoraptera", marker="COI-5P")
##write.table(Zoraptera, file = "/home/orourke/R/Zoraptera_taxmap_COI.txt", sep = "\t")
##rm(Zoraptera)

##all arthropods not insects
Arachnida <- bold_seqspec(taxon="Arachnida", marker="COI-5P")
write.table(Arachnida, file = "/home/orourke/R/Arachnida_taxmap_COI.txt", sep = "\t")
rm(Arachnida)
Branchiopoda <- bold_seqspec(taxon="Branchiopoda", marker="COI-5P")
write.table(Branchiopoda, file = "/home/orourke/R/Branchiopoda_taxmap_COI.txt", sep = "\t")
rm(Branchiopoda)
Cephalocarida <- bold_seqspec(taxon="Cephalocarida", marker="COI-5P")
write.table(Cephalocarida, file = "/home/orourke/R/Cephalocarida_taxmap_COI.txt", sep = "\t")
rm(Cephalocarida)
Chilopoda <- bold_seqspec(taxon="Chilopoda", marker="COI-5P")
write.table(Chilopoda, file = "/home/orourke/R/Chilopoda_taxmap_COI.txt", sep = "\t")
rm(Chilopoda)
Collembola <- bold_seqspec(taxon="Collembola", marker="COI-5P")
write.table(Collembola, file = "/home/orourke/R/Collembola_taxmap_COI.txt", sep = "\t")
rm(Collembola)
Diplopoda <- bold_seqspec(taxon="Diplopoda", marker="COI-5P")
write.table(Diplopoda, file = "/home/orourke/R/Diplopoda_taxmap_COI.txt", sep = "\t")
rm(Diplopoda)
Diplura <- bold_seqspec(taxon="Diplura", marker="COI-5P")
write.table(Diplura, file = "/home/orourke/R/Diplura_taxmap_COI.txt", sep = "\t")
rm(Diplura)
Malacostraca <- bold_seqspec(taxon="Malacostraca", marker="COI-5P")
write.table(Malacostraca, file = "/home/orourke/R/Malacostraca_taxmap_COI.txt", sep = "\t")
rm(Malacostraca)
Maxillopoda <- bold_seqspec(taxon="Maxillopoda", marker="COI-5P")
write.table(Maxillopoda, file = "/home/orourke/R/Maxillopoda_taxmap_COI.txt", sep = "\t")
rm(Maxillopoda)
Merostomata <- bold_seqspec(taxon="Merostomata", marker="COI-5P")
write.table(Merostomata, file = "/home/orourke/R/Merostomata_taxmap_COI.txt", sep = "\t")
rm(Merostomata)
Ostracoda <- bold_seqspec(taxon="Ostracoda", marker="COI-5P")
write.table(Ostracoda, file = "/home/orourke/R/Ostracoda_taxmap_COI.txt", sep = "\t")
rm(Ostracoda)
Pauropoda <- bold_seqspec(taxon="Pauropoda", marker="COI-5P")
write.table(Pauropoda, file = "/home/orourke/R/Pauropoda_taxmap_COI.txt", sep = "\t")
rm(Pauropoda)

##Pentastomida <- bold_seqspec(taxon="Pentastomida", marker="COI-5P")
##write.table(Pentastomida, file = "/home/orourke/R/Pentastomida_taxmap_COI.txt", sep = "\t")
##rm(Pentastomida)
Protura <- bold_seqspec(taxon="Protura", marker="COI-5P")
write.table(Protura, file = "/home/orourke/R/Protura_taxmap_COI.txt", sep = "\t")
rm(Protura)
Pycnogonida <- bold_seqspec(taxon="Pycnogonida", marker="COI-5P")
write.table(Pycnogonida, file = "/home/orourke/R/Pycnogonida_taxmap_COI.txt", sep = "\t")
rm(Pycnogonida)
Remipedia <- bold_seqspec(taxon="Remipedia", marker="COI-5P")
write.table(Remipedia, file = "/home/orourke/R/Remipedia_taxmap_COI.txt", sep = "\t")
rm(Remipedia)
Symphyla <- bold_seqspec(taxon="Symphyla", marker="COI-5P")
write.table(Symphyla, file = "/home/orourke/R/Symphyla_taxmap_COI.txt", sep = "\t")
rm(Symphyla)

#all animals not arthropods
Acanthocephala <- bold_seqspec(taxon="Acanthocephala", marker="COI-5P")
write.table(Acanthocephala, file = "/home/orourke/R/Acanthocephala_taxmap_COI.txt", sep = "\t")
rm(Acanthocephala)
Annelida <- bold_seqspec(taxon="Annelida", marker="COI-5P")
write.table(Annelida, file = "/home/orourke/R/Annelida_taxmap_COI.txt", sep = "\t")
rm(Annelida)
Brachiopoda <- bold_seqspec(taxon="Brachiopoda", marker="COI-5P")
write.table(Brachiopoda, file = "/home/orourke/R/Brachiopoda_taxmap_COI.txt", sep = "\t")
rm(Brachiopoda)
Bryozoa <- bold_seqspec(taxon="Bryozoa", marker="COI-5P")
write.table(Bryozoa, file = "/home/orourke/R/Bryozoa_taxmap_COI.txt", sep = "\t")
rm(Bryozoa)
Chaetognatha <- bold_seqspec(taxon="Chaetognatha", marker="COI-5P")
write.table(Chaetognatha, file = "/home/orourke/R/Chaetognatha_taxmap_COI.txt", sep = "\t")
rm(Chaetognatha)
Chordata <- bold_seqspec(taxon="Chordata", marker="COI-5P")
write.table(Chordata, file = "/home/orourke/R/Chordata_taxmap_COI.txt", sep = "\t")
rm(Chordata)
Cnidaria <- bold_seqspec(taxon="Cnidaria", marker="COI-5P")
write.table(Cnidaria, file = "/home/orourke/R/Cnidaria_taxmap_COI.txt", sep = "\t")
rm(Cnidaria)
Cycliophora <- bold_seqspec(taxon="Cycliophora", marker="COI-5P")
write.table(Cycliophora, file = "/home/orourke/R/Cycliophora_taxmap_COI.txt", sep = "\t")
rm(Cycliophora)
Echinodermata <- bold_seqspec(taxon="Echinodermata", marker="COI-5P")
write.table(Echinodermata, file = "/home/orourke/R/Echinodermata_taxmap_COI.txt", sep = "\t")
rm(Echinodermata)
Echiura <- bold_seqspec(taxon="Echiura", marker="COI-5P")
write.table(Echiura, file = "/home/orourke/R/Echiura_taxmap_COI.txt", sep = "\t")
rm(Echiura)
Gnathostomulida <- bold_seqspec(taxon="Gnathostomulida", marker="COI-5P")
write.table(Gnathostomulida, file = "/home/orourke/R/Gnathostomulida_taxmap_COI.txt", sep = "\t")
rm(Gnathostomulida)
Hemichordata <- bold_seqspec(taxon="Hemichordata", marker="COI-5P")
write.table(Hemichordata, file = "/home/orourke/R/Hemichordata_taxmap_COI.txt", sep = "\t")
rm(Hemichordata)
Mollusca <- bold_seqspec(taxon="Mollusca", marker="COI-5P")
write.table(Mollusca, file = "/home/orourke/R/Mollusca_taxmap_COI.txt", sep = "\t")
rm(Mollusca)
Nematoda <- bold_seqspec(taxon="Nematoda", marker="COI-5P")
write.table(Nematoda, file = "/home/orourke/R/Nematoda_taxmap_COI.txt", sep = "\t")
rm(Nematoda)
Nemertea <- bold_seqspec(taxon="Nemertea", marker="COI-5P")
write.table(Nemertea, file = "/home/orourke/R/Nemertea_taxmap_COI.txt", sep = "\t")
rm(Nemertea)
Onychophora <- bold_seqspec(taxon="Onychophora", marker="COI-5P")
write.table(Onychophora, file = "/home/orourke/R/Onychophora_taxmap_COI.txt", sep = "\t")
rm(Onychophora)
Platyhelminthes <- bold_seqspec(taxon="Platyhelminthes", marker="COI-5P")
write.table(Platyhelminthes, file = "/home/orourke/R/Platyhelminthes_taxmap_COI.txt", sep = "\t")
rm(Platyhelminthes)
Porifera <- bold_seqspec(taxon="Porifera", marker="COI-5P")
write.table(Porifera, file = "/home/orourke/R/Porifera_taxmap_COI.txt", sep = "\t")
rm(Porifera)
Priapulida <- bold_seqspec(taxon="Priapulida", marker="COI-5P")
write.table(Priapulida, file = "/home/orourke/R/Priapulida_taxmap_COI.txt", sep = "\t")
rm(Priapulida)
Rotifera <- bold_seqspec(taxon="Rotifera", marker="COI-5P")
write.table(Rotifera, file = "/home/orourke/R/Rotifera_taxmap_COI.txt", sep = "\t")
rm(Rotifera)
Sipuncula <- bold_seqspec(taxon="Sipuncula", marker="COI-5P")
write.table(Sipuncula, file = "/home/orourke/R/Sipuncula_taxmap_COI.txt", sep = "\t")
rm(Sipuncula)
Tardigrada <- bold_seqspec(taxon="Tardigrada", marker="COI-5P")
write.table(Tardigrada, file = "/home/orourke/R/Tardigrada_taxmap_COI.txt", sep = "\t")
rm(Tardigrada)
Xenoturbellida <- bold_seqspec(taxon="Xenoturbellida", marker="COI-5P")
write.table(Xenoturbellida, file = "/home/orourke/R/Xenoturbellida_taxmap_COI.txt", sep = "\t")
rm(Xenoturbellida)
